In [ ]:
# Question (and screen share test): 
# Will problem solving session help improve PSP?
# Yes or no?

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.stats import ttest_rel

In [2]:
df_ps = pd.read_csv("problem_solving.csv")

In [3]:
df_ps

      id  test_1  test_2
0      0      40      38
1      1      49      44
2      2      65      69
3      3      59      63
4      4      44      43
..   ...     ...     ...
132  132      45      44
133  133      46      42
134  134      40      35
135  135      60      66
136  136      79      84

[137 rows x 3 columns]

In [5]:
df_ps.describe()

               id      test_1      test_2
count  137.000000  137.000000  137.000000
mean    68.000000   60.489051   62.430657
std     39.692569   17.080311   17.516293
min      0.000000   30.000000   27.000000
25%     34.000000   46.000000   48.000000
50%     68.000000   59.000000   62.000000
75%    102.000000   75.000000   77.000000
max    136.000000   89.000000   96.000000

In [6]:
# H0: No difference in mean
ttest_rel(df_ps["test_1"], df_ps["test_2"])
# p-value is small -- reject null hypothesis

TtestResult(statistic=-5.502886353508166, pvalue=1.795840353792307e-07, df=136)